// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQh8farln2jUaVbMnUv9fThNpZKvUue88',
    appId: '1:826030113436:web:664b03ac2c609d27672359',
    messagingSenderId: '826030113436',
    projectId: 'expense-tracker-784f0',
    authDomain: 'expense-tracker-784f0.firebaseapp.com',
    storageBucket: 'expense-tracker-784f0.appspot.com',
    measurementId: 'G-TCCQ8KY4E7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDupKFiLOaOVO9izmaQCrrtbOOV4qMlIhA',
    appId: '1:826030113436:android:9ceece0a6dddf1b9672359',
    messagingSenderId: '826030113436',
    projectId: 'expense-tracker-784f0',
    storageBucket: 'expense-tracker-784f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUKS0sAYiWsIVk_YIAA9nsHr5xAJDtmM8',
    appId: '1:826030113436:ios:e3fef2c27248ee5e672359',
    messagingSenderId: '826030113436',
    projectId: 'expense-tracker-784f0',
    storageBucket: 'expense-tracker-784f0.appspot.com',
    iosBundleId: 'com.example.expensesTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUKS0sAYiWsIVk_YIAA9nsHr5xAJDtmM8',
    appId: '1:826030113436:ios:e3fef2c27248ee5e672359',
    messagingSenderId: '826030113436',
    projectId: 'expense-tracker-784f0',
    storageBucket: 'expense-tracker-784f0.appspot.com',
    iosBundleId: 'com.example.expensesTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQh8farln2jUaVbMnUv9fThNpZKvUue88',
    appId: '1:826030113436:web:46c5568f5846769b672359',
    messagingSenderId: '826030113436',
    projectId: 'expense-tracker-784f0',
    authDomain: 'expense-tracker-784f0.firebaseapp.com',
    storageBucket: 'expense-tracker-784f0.appspot.com',
    measurementId: 'G-EVRXHR8127',
  );
}
